name: Air Corsica UDT Pipeline

on:
  schedule:
    - cron: '0 7 * * *'  # Tous les jours à 07:00 UTC
  workflow_dispatch:      # Permet un lancement manuel depuis l'interface GitHub

jobs:
  run-pipeline:
    runs-on: ubuntu-latest  # Utilise un runner cloud GitHub géré automatiquement
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Execute run script
        run: |
          chmod +x ./run.sh
          ./run.sh
