name: Air Corsica UDT Pipeline

on:
  schedule:
    - cron: '2 7 * * *'  # Déclenché à 07:02 UTC pour fuir l'affluence de 07:00
  workflow_dispatch:      # Permet un lancement manuel depuis l'interface GitHub

jobs:
  run-pipeline:
    runs-on: ubuntu-latest  # Utilise un runner cloud GitHub géré automatiquement
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Execute run script
        run: |
          chmod +x ./run.sh
          ./run.sh
